Praktek BOW
=============================

***Universitas Dian Nuswantoro***

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('clean_dataset_stem.csv',sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'clean_dataset_stem.csv'

In [3]:
dataset.shape

NameError: name 'dataset' is not defined

In [4]:
dataset.head(10)

NameError: name 'dataset' is not defined

In [5]:
dataset_feature = dataset['ProcessedText'].astype(str)

NameError: name 'dataset' is not defined

In [6]:
dataset_label = dataset['Sentimen']

NameError: name 'dataset' is not defined

In [7]:
dataset_feature

NameError: name 'dataset_feature' is not defined

In [8]:
dataset_label

NameError: name 'dataset_label' is not defined

# cek distribusi label

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
# Visualizing the target variable
plt.figure(figsize=(12,8))
sns.distplot(dataset_label, label=f'target, skew: {dataset_label.skew():.2f}')
plt.legend(loc='best')
plt.show()

NameError: name 'dataset_label' is not defined

<Figure size 1200x800 with 0 Axes>

In [11]:
dataset_label.value_counts()

NameError: name 'dataset_label' is not defined

# BOW

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
vectorizer = CountVectorizer()

In [14]:
X = vectorizer.fit_transform(dataset_feature)

NameError: name 'dataset_feature' is not defined

In [15]:
print(vectorizer.get_feature_names())

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [16]:
print(X.toarray())

NameError: name 'X' is not defined

In [17]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [18]:
X2 = vectorizer2.fit_transform(dataset_feature)

NameError: name 'dataset_feature' is not defined

In [19]:
print(vectorizer2.get_feature_names())

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [20]:
print(X2.toarray())

NameError: name 'X2' is not defined

### Simulasi Corpus

In [21]:
corpus = [
    'This is the first Document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [22]:
vectorizer = CountVectorizer()

In [23]:
Z = vectorizer.fit_transform(corpus)

In [24]:
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [25]:
print(Z.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [26]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [27]:
Z2 = vectorizer2.fit_transform(corpus)

In [28]:
vectorizer2.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [29]:
print(Z2.toarray())

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]
